"""Callback interfaces, matching the C# SDK's ``I*Callbacks``.

Subclass any of these, override what you need, and register the instance with
:meth:`RealtimeClient.add_callback_target`. All methods default to no-ops.
"""

from typing import Any, Dict, List

from pyphotonrealtime.peer import EventData
from pyphotonrealtime.realtime.player import Player
from pyphotonrealtime.realtime.room import RoomInfo
from pyphotonrealtime.realtime.state import DisconnectCause


class ConnectionCallbacks:
    def on_connected(self) -> None: ...
    def on_connected_to_master(self) -> None: ...
    def on_disconnected(self, cause: DisconnectCause) -> None: ...
    def on_region_list_received(self, regions: Dict[str, str]) -> None: ...
    def on_custom_authentication_response(self, data: Dict[str, Any]) -> None: ...
    def on_custom_authentication_failed(self, debug_message: str) -> None: ...


class MatchmakingCallbacks:
    def on_friend_list_update(self, friends: List[Any]) -> None: ...
    def on_created_room(self) -> None: ...
    def on_create_room_failed(self, return_code: int, message: str) -> None: ...
    def on_joined_room(self) -> None: ...
    def on_join_room_failed(self, return_code: int, message: str) -> None: ...
    def on_join_random_failed(self, return_code: int, message: str) -> None: ...
    def on_left_room(self) -> None: ...


class LobbyCallbacks:
    def on_joined_lobby(self) -> None: ...
    def on_left_lobby(self) -> None: ...
    def on_room_list_update(self, rooms: List[RoomInfo]) -> None: ...
    def on_lobby_statistics_update(self, stats: List[Any]) -> None: ...


class InRoomCallbacks:
    def on_player_entered_room(self, player: Player) -> None: ...
    def on_player_left_room(self, player: Player) -> None: ...
    def on_room_properties_update(self, changed: Dict[Any, Any]) -> None: ...
    def on_player_properties_update(
        self, player: Player, changed: Dict[Any, Any]
    ) -> None: ...
    def on_master_client_switched(self, new_master: Player) -> None: ...


class OnEventCallback:
    def on_event(self, event: EventData) -> None: ...
